HOST: http://e3.nctu.edu.tw/mService/service.asmx

--- E3 Mobile API ---
---
* You must obtain **LoginTicket** (and some require **AccountID**) using *Login* API
* Content-Type of all request must be *application/x-www-form-urlencoded*
* Content-Type of all response is *text/xml; charset=utf-8*
---

-- Login --
Login
POST /Login
> Content-Type: application/x-www-form-urlencoded
account=0123456&password=Password1
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<AccountData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://mService.e3.nctu.edu.tw/">
  <LoginTicket>xxxxxxxx</LoginTicket>
  <AccountId>xxxxxxx</AccountId>
  <DepartId>xxxxxxxx</DepartId>
  <AccountStatus>1</AccountStatus>
  <Account>0123456</Account>
  <Sex>1</Sex>
  <Name>OOO</Name>
  <EMail>aaa@gmail.com</EMail>
  <PersonalId>A123456789</PersonalId>
  <OfficeTitle>XXXX</OfficeTitle>
  <Class>*</Class>
  <Tel>0912345678</Tel>
  <MSNAccount />
  <Mobile />
  <ZipCode />
  <Address />
  <Url />
  <Password>XXXXX</Password>
  <CmsSrvId>XXX</CmsSrvId>
  <IsGraduation>true</IsGraduation>
  <StudentRole>0</StudentRole>
  <Degree>2</Degree>
  <TakenSemester>1</TakenSemester>
  <StudentYear>0</StudentYear>
  <IsInThisSchool>true</IsInThisSchool>
  <SmtpServer>m-smtp.nctu.edu.tw</SmtpServer>
  <SmtpPort>25</SmtpPort>
  <SmtpNeedLogin>false</SmtpNeedLogin>
  <SmtpAccount />
  <SmtpPassword />
  <SpecAccount />
  <CheckEMail>true</CheckEMail>
  <OfficeLab />
  <NickName />
  <Introduce />
  <PhotoOpenStatus>false</PhotoOpenStatus>
  <UserRole />
  <RoleName />
</AccountData>

--
Course
Course related API
--

Get personal basic information
POST /GetPersonalCoursePosition
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXX&accountId=XXX
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfCoursePositionStatus 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/">
    <CoursePositionStatus>
        <CrsYear>102</CrsYear>
        <CrsSemester>1</CrsSemester>
        <Role>修課生</Role>
    </CoursePositionStatus>
</ArrayOfCoursePositionStatus>

Get course list
POST /GetCourseList
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXX&accountId=XXX&role=stu
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfCourseData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://mService.e3.nctu.edu.tw/">
  <CourseData>
    <CourseId>XXX</CourseId>
    <PmtCrsNo>XXX1111</PmtCrsNo>
    <CourseNo>0000</CourseNo>
    <CourseName>OOOO</CourseName>
    <CrsYear>102</CrsYear>
    <CrsSemester>上</CrsSemester>
    <TeacherName>AAA</TeacherName>
    <ForumEnable>false</ForumEnable>
    <OldCourse>false</OldCourse>
    <UserRole>stu</UserRole>
    <PositionStatus>0</PositionStatus>
  </CourseData>
  <CourseData>
    <CourseId>XXX2</CourseId>
    <PmtCrsNo>XXX1111</PmtCrsNo>
    <CourseNo>0000</CourseNo>
    <CourseName>OOOO</CourseName>
    <CrsYear>102</CrsYear>
    <CrsSemester>上</CrsSemester>
    <TeacherName>AAA</TeacherName>
    <ForumEnable>false</ForumEnable>
    <OldCourse>false</OldCourse>
    <UserRole>stu</UserRole>
    <PositionStatus>0</PositionStatus>
  </CourseData>
</ArrayOfCourseData>

Get course time

Sample course on 1EF at ED000
POST /GetCourseTime
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXX&courseId=XXXX
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfCourseTimeData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/">
    <CourseTimeData>
        <CourseId>XXXX</CourseId>
        <WeekDay>1</WeekDay>
        <Section>E</Section>
        <RoomNo>ED000       </RoomNo>
        <CourseName>OOOO</CourseName>
    </CourseTimeData>
    <CourseTimeData>
        <CourseId>XXXX</CourseId>
        <WeekDay>1</WeekDay>
        <Section>F</Section>
        <RoomNo>ED116       </RoomNo>
        <CourseName>OOOO</CourseName>
    </CourseTimeData>
</ArrayOfCourseTimeData>

-- Announcement --
Get announcement

* bulType=1: Latest announcement
* bulType=2: Old announcement
POST /GetStuAnnouncementList
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXX&courseId=XXXX&bulType=1
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfBulletinData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/">
    <BulletinData>
        <BulletinId>XXXX</BulletinId>
        <CourseId>XXXX</CourseId>
        <BulType>1</BulType>
        <Caption>Title</Caption>
        <Content>Content</Content>
        <BeginDate>2013/08/20</BeginDate>
        <EndDate>2014/01/17</EndDate>
        <NotifyType>2</NotifyType>
        <NeedVote>0</NeedVote>
        <ExpiredStatus>0</ExpiredStatus>
        <CourseName />
        <AttatchFileName />
    </BulletinData>
</ArrayOfBulletinData>

-- Documents --
Get document list

* docType=1: Handout
* docType=2: Reference
POST /GetMaterialDocList
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXX&courseId=XXXX&docType=1
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfMaterialDocData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/">
    <MaterialDocData>
        <UnitStatus>1</UnitStatus>
        <UnitName />
        <DisplayName>Title</DisplayName>
        <TreeNodeId>XXXXX</TreeNodeId>
        <DocOrder>2</DocOrder>
        <UnitOrder>99999</UnitOrder>
        <BeginDate>2013/06/20</BeginDate>
        <EndDate>2014/02/28</EndDate>
        <CourseBeginDate>2013/06/20</CourseBeginDate>
        <CourseEndDate>2014/02/28</CourseEndDate>
        <IsViewGuest>false</IsViewGuest>
        <DocumentId>XXXXXX</DocumentId>
        <LibaryDocumentId>XXXX</LibaryDocumentId>
        <ParentTreeNodeId>XXXX</ParentTreeNodeId>
        <OpenState>2</OpenState>
        <Summary />
        <CourseName />
        <mServiceBaseUrl>http://140.113.8.80/mService</mServiceBaseUrl>
        <CourseId>XXXX</CourseId>
    </MaterialDocData>
</ArrayOfMaterialDocData>

Get Attachment File List

* resId: DocumentId from Document List
* metaType: Unknown, set to 10
POST /GetAttachFileList
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXX&resId=DocumentID&metaType=10&courseId=XXXX
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfAttachFileInfoData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/">
    <AttachFileInfoData>
        <MediaCategory>2</MediaCategory>
        <AttachMediaId>XXXXX</AttachMediaId>
        <ContentMediaId>XXXXX</ContentMediaId>
        <DisplayFileName>FileName</DisplayFileName>
        <RealityFileName>Link</RealityFileName>
        <MimeType>application/pdf</MimeType>
        <FileSize>263814</FileSize>
        <Description />
        <CreateTime>2013/09/15 08:41:50</CreateTime>
        <SourceAttachId />
        <IsViewGuest>0</IsViewGuest>
    </AttachFileInfoData>
</ArrayOfAttachFileInfoData>

-- Assignments --
Get Assignment List

* listType=1:待繳
* listType=2:互評
* listType=3:過期
* listType=4:已繳
POST /GetStuHomeworkList
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXXX&courseId=XXXX&accountId=XXXX&listType=1
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfHomeworkData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/" />

-- Discussion --
-- E-Mail --
-- Score --
-- Members --
Get Member List

* role=tea:老師/助教
* role=stu:旁聽生
* role=ta:學生
POST /GetMemberList
> Content-Type: application/x-www-form-urlencoded
loginTicket=XXXX&courseId=XXXX&role=tea
< 200
< Content-Type: text/xml; charset=utf-8
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfAccountData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://mService.e3.nctu.edu.tw/">
    <AccountData>
        <LoginTicket />
        <AccountId>XXX</AccountId>
        <DepartId>XXX</DepartId>
        <AccountStatus xsi:nil="true" />
        <Account>XXX</Account>
        <Sex xsi:nil="true" />
        <Name>XXXX</Name>
        <EMail>aaa@gmail.com</EMail>
        <PersonalId />
        <OfficeTitle />
        <Class />
        <Tel>(無)</Tel>
        <MSNAccount />
        <Mobile />
        <ZipCode />
        <Address />
        <Url />
        <Password />
        <CmsSrvId />
        <IsGraduation xsi:nil="true" />
        <StudentRole xsi:nil="true" />
        <Degree xsi:nil="true" />
        <TakenSemester xsi:nil="true" />
        <StudentYear xsi:nil="true" />
        <IsInThisSchool xsi:nil="true" />
        <SmtpServer />
        <SmtpPort xsi:nil="true" />
        <SmtpNeedLogin xsi:nil="true" />
        <SmtpAccount />
        <SmtpPassword />
        <SpecAccount />
        <CheckEMail xsi:nil="true" />
        <OfficeLab />
        <NickName />
        <Introduce />
        <PhotoOpenStatus xsi:nil="true" />
        <UserRole>mtea</UserRole>
        <RoleName>&amp;nbsp;(主開課教師)</RoleName>
    </AccountData>
</ArrayOfAccountData>